# Generated by Django 6.0.2 on 2026-02-15 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_add_platform_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player1_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Suspicious account; blocks withdrawals'),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='platformrevenue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='platformrevenue',
            name='match',
            field=models.ForeignKey(blank=True, help_text='Null for quick-play vs AI', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.match'),
        ),
    ]
