# Generated by Django 6.0.2 on 2026-02-12 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_match_player1_remove_match_player1_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_payment_charge_id', models.CharField(max_length=255, unique=True)),
                ('provider_payment_charge_id', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('coins_credited', models.IntegerField()),
                ('status', models.CharField(default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.user')),
            ],
        ),
    ]
