# Generated by Django 5.2.4 on 2026-02-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_monetization_phases'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payload_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(help_text='Amount in Stars (XTR)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_payment_charge_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='telegram_payment_charge_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
